# Generated by Django 5.0.7 on 2024-10-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=255)),
                ('email', models.EmailField(default='example@example.com', max_length=254, unique=True)),
                ('mobile', models.CharField(default='0000000000', max_length=15)),
                ('specialization', models.CharField(max_length=150)),
                ('schedule', models.CharField(max_length=150)),
                ('details', models.TextField()),
                ('consulting_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profile_picture', models.ImageField(upload_to='doctor_profile_picture/')),
                ('category', models.CharField(choices=[('doctor', 'Doctor'), ('geriatric_counselor', 'Geriatric Counselor')], default='doctor', max_length=50)),
            ],
        ),
    ]
