# Generated by Django 5.0.7 on 2024-07-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0003_doctorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='mobile',
            field=models.CharField(default='0000000000', max_length=15),
        ),
    ]
