# Generated by Django 5.0.7 on 2024-08-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0005_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='category',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('geriatric_counselor', 'Geriatric Counselor')], default='doctor', max_length=50),
        ),
    ]
