# Generated by Django 5.0.7 on 2024-08-22 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0007_alter_timeslot_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_side.doctorprofile'),
        ),
    ]
