# Generated by Django 5.0.7 on 2025-01-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0009_bookedslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('text', 'Text Input'), ('multiple_choice', 'Multiple Choice'), ('puzzle', 'Puzzle'), ('drag_drop', 'Drag and Drop'), ('image_click', 'Image Click')], max_length=20)),
                ('options', models.JSONField(blank=True, null=True)),
                ('correct_answer', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
