# Generated by Django 4.1.13 on 2024-07-10 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0002_customuser_is_superuser_customuser_last_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
