# Generated by Django 4.1.13 on 2024-07-11 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
    ]
