# Generated by Django 5.0.7 on 2024-08-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0004_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiries',
            name='message',
            field=models.TextField(),
        ),
    ]
