# Generated by Django 5.0.7 on 2024-08-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0005_alter_enquiries_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='meet_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
