# Generated by Django 5.0.7 on 2024-09-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0008_firstpersonclientdetails_assessment_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstpersonclientdetails',
            name='message',
        ),
        migrations.RemoveField(
            model_name='firstpersonclientdetails',
            name='mobile',
        ),
        migrations.AddField(
            model_name='firstpersonclientdetails',
            name='interpretation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
