# Generated by Django 5.0.7 on 2024-10-10 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0011_newslettersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstpersonclientdetails',
            name='assessment_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
