# Generated by Django 5.0.7 on 2024-10-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0013_firstpersonclientdetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstpersonclientdetails',
            name='age',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='firstpersonclientdetails',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
