# Generated by Django 5.0.7 on 2025-02-01 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0015_userassessment_userresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='question',
        ),
        migrations.DeleteModel(
            name='UserAssessment',
        ),
        migrations.DeleteModel(
            name='UserResponse',
        ),
    ]
